name: demo-workflow.yaml
on: 
  push:
    branches:
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2.4.2

        # Login Docker Hub
        - name: Login to DockerHub
          uses: docker/login-action@v2.0.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Build and Push Image
        - name: Build and Push Docker Image
          uses: mr-smithers-excellent/docker-build-push@v5
          with:
            image: sarkartanmay393/portfolio-web
            registry: docker.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            
        - name: Image Digest
          run: echo ${{ steps.docker_build.outputs.digest }}
        # Deploy to Firebase hosting.
        - name: Deploy Website
          uses: danielmillan/pipelines-firebase-hosting@1.0.8
          with:
            firebase-token: ${{ secrets.FIREBASE_TOKEN }}
            resources-name: build/web
            project-name: Portfolio-Web


