name: demo-workflow.yaml
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
#       - run: sudo snap install flutter --classic
#       - run: flutter sdk-path
      - run: pwd
      - run: cd ..
      - run: pwd
      - run: ls --color=always
#       - run: flutter analyze
#       - run: flutter build web --release
#       - run: cd build/web
      - run: pwd
