name: demo-workflow.yaml
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
        - uses: action/checkout@v2
        - run: sudo snap install flutter --classic
        - run: flutter sdk-path
        - run: flutter test

