name: demo-workflow.yaml
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
        - run: git clone https://github.com/sarkartanmay393/Portfolio-Web.git
        - run: cd Portfolio-Web
        - run: ls
        - run: cd Portfolio-Web
        - run: ls
        - run: sudo snap install flutter --classic
        - run: flutter sdk-path
        - run: flutter analyze
        - run: flutter build web --release
        - run: cd build/web
